const { DataTypes, id, defineModel } = require('./helpers');

module.exports = (db) =>
  defineModel(
    db,
    'GatePass',
    {
      id: id(),
      number: { type: DataTypes.STRING(100), allowNull: false, unique: true },
      token: { type: DataTypes.STRING, allowNull: false, unique: true },
      sourceType: { type: DataTypes.ENUM('SALE', 'PURCHASE'), allowNull: false },
      sale: { type: DataTypes.STRING(24), field: 'sale_id' },
      purchase: { type: DataTypes.STRING(24), field: 'purchase_id' },
      documentNumber: { type: DataTypes.STRING(100), allowNull: false },
      warehouse: { type: DataTypes.STRING(24), allowNull: false, field: 'warehouse_id' },
      saleDate: { type: DataTypes.DATE, allowNull: false },
      customer: { type: DataTypes.STRING(24), field: 'customer_id' },
      customerName: DataTypes.STRING(120),
      customerPhone: { type: DataTypes.STRING(30), allowNull: false, defaultValue: '' },
      customerEmail: { type: DataTypes.STRING(120), allowNull: false, defaultValue: '' },
      customerAddress: { type: DataTypes.STRING(300), allowNull: false, defaultValue: '' },
      vendor: { type: DataTypes.STRING(24), field: 'vendor_id' },
      vendorName: DataTypes.STRING(120),
      vendorPhone: { type: DataTypes.STRING(30), allowNull: false, defaultValue: '' },
      vendorEmail: { type: DataTypes.STRING(120), allowNull: false, defaultValue: '' },
      vendorAddress: { type: DataTypes.STRING(300), allowNull: false, defaultValue: '' },
      pricingSubtotal: DataTypes.BIGINT,
      pricingDiscount: DataTypes.BIGINT,
      pricingTaxPercent: DataTypes.DECIMAL(9, 4),
      pricingTax: DataTypes.BIGINT,
      pricingTotal: DataTypes.BIGINT,
      status: {
        type: DataTypes.ENUM('PENDING', 'PROCESSED', 'CANCELLED'),
        allowNull: false,
        defaultValue: 'PENDING',
      },
      driver: DataTypes.JSONB,
      loadNotes: { type: DataTypes.TEXT, allowNull: false, defaultValue: '' },
      signatureData: DataTypes.TEXT,
      processedAt: DataTypes.DATE,
      processedBy: { type: DataTypes.STRING(24), field: 'processed_by_id' },
      lastEditedAt: DataTypes.DATE,
      lastEditedBy: { type: DataTypes.STRING(24), field: 'last_edited_by_id' },
      createdBy: { type: DataTypes.STRING(24), field: 'created_by_id' },
    },
    { tableName: 'gate_passes' },
  );
