const { ROLES } = require('../utils/constants');
const { PERMISSIONS, WILDCARD } = require('../utils/permissions');

const SYSTEM_ROLES = [
  {
    name: ROLES.CASHIER,
    description: 'Point-of-sale operator',
    permissions: [
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_CREATE,
    ],
  },
  {
    name: ROLES.ACCOUNTANT,
    description: 'Finance / reporting',
    permissions: [
      PERMISSIONS.VENDORS_READ,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.PURCHASES_READ,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.INVOICES_READ,
      PERMISSIONS.FINANCE_READ,
      PERMISSIONS.FINANCE_MANAGE,
      PERMISSIONS.REPORTS_READ,
    ],
  },
  {
    name: ROLES.MANAGER,
    description: 'Can view staff and run day-to-day operations',
    permissions: [
      PERMISSIONS.USERS_READ,
      PERMISSIONS.VENDORS_READ,
      PERMISSIONS.VENDORS_CREATE,
      PERMISSIONS.VENDORS_UPDATE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.INVENTORY_MANAGE,
      PERMISSIONS.PURCHASES_READ,
      PERMISSIONS.PURCHASES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.INVOICES_READ,
      PERMISSIONS.INVOICES_CREATE,
      PERMISSIONS.FINANCE_READ,
      PERMISSIONS.REPORTS_READ,
    ],
  },
  {
    name: ROLES.ADMIN,
    description: 'Manages staff accounts, operations and finance',
    permissions: [
      PERMISSIONS.USERS_READ,
      PERMISSIONS.USERS_CREATE,
      PERMISSIONS.USERS_UPDATE,
      PERMISSIONS.USERS_UPDATE_ROLE,
      PERMISSIONS.USERS_SET_ACTIVE,
      PERMISSIONS.USERS_DELETE,
      PERMISSIONS.VENDORS_READ,
      PERMISSIONS.VENDORS_CREATE,
      PERMISSIONS.VENDORS_UPDATE,
      PERMISSIONS.VENDORS_DELETE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.INVENTORY_MANAGE,
      PERMISSIONS.PURCHASES_READ,
      PERMISSIONS.PURCHASES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.INVOICES_READ,
      PERMISSIONS.INVOICES_CREATE,
      PERMISSIONS.FINANCE_READ,
      PERMISSIONS.FINANCE_MANAGE,
      PERMISSIONS.REPORTS_READ,
      PERMISSIONS.SETTINGS_READ,
      PERMISSIONS.SETTINGS_MANAGE,
    ],
  },
  {
    name: ROLES.SUPER_ADMIN,
    description: 'Full access, including role management',
    permissions: [WILDCARD],
  },
];

const CATEGORIES = ['Electronics', 'Accessories', 'Office Supplies'];
const BRANDS = ['Logitech', 'Keychron', 'Generic'];
const UNITS = [
  { name: 'Piece', abbreviation: 'pc' },
  { name: 'Box', abbreviation: 'box' },
];

module.exports = { SYSTEM_ROLES, CATEGORIES, BRANDS, UNITS };
